/* Verilog module instantiation template generated by SCUBA Diamond_2.2_Production (99) */
/* Module Version: 1.1 */
/* Thu Aug 29 17:42:34 2013 */

/* parameterized module instance */
customSPI __ (.wb_clk_i( ), .wb_rst_i( ), .wb_cyc_i( ), .wb_stb_i( ), 
    .wb_we_i( ), .wb_adr_i( ), .wb_dat_i( ), .wb_dat_o( ), .wb_ack_o( ), 
    .spi_clk( ), .spi_miso( ), .spi_mosi( ), .spi_scsn( ));
