/* Verilog module instantiation template generated by SCUBA Diamond_2.2_Production (99) */
/* Module Version: 1.1 */
/* Thu Aug 29 17:45:54 2013 */

/* parameterized module instance */
customI2C __ (.wb_clk_i( ), .wb_rst_i( ), .wb_cyc_i( ), .wb_stb_i( ), 
    .wb_we_i( ), .wb_adr_i( ), .wb_dat_i( ), .wb_dat_o( ), .wb_ack_o( ), 
    .i2c2_scl( ), .i2c2_sda( ), .i2c2_irqo( ));
