/* Verilog netlist generated by SCUBA Diamond_2.2_Production (99) */
/* Module Version: 4.3 */
/* C:\lscc\diamond\2.2_x64\ispfpga\bin\nt64\scuba.exe -w -n PMcounter -lang verilog -synth synplify -bus_exp 7 -bl -arch xo2c00 -type counter -up -width 32 -cnt_low 0 -cnt_up 4294967295 -e  */
/* Thu Aug 29 17:31:14 2013 */


`timescale 1 ns / 1 ps
module PMcounter (Clock, Clk_En, Aclr, Q)/* synthesis NGD_DRC_MASK=1 */;
    input wire Clock;
    input wire Clk_En;
    input wire Aclr;
    output wire [0:31] Q;

    wire scuba_vlo;
    wire scuba_vhi;
    wire idataout0;
    wire idataout1;
    wire cnt_ci;
    wire idataout2;
    wire idataout3;
    wire co0;
    wire idataout4;
    wire idataout5;
    wire co1;
    wire idataout6;
    wire idataout7;
    wire co2;
    wire idataout8;
    wire idataout9;
    wire co3;
    wire idataout10;
    wire idataout11;
    wire co4;
    wire idataout12;
    wire idataout13;
    wire co5;
    wire idataout14;
    wire idataout15;
    wire co6;
    wire idataout16;
    wire idataout17;
    wire co7;
    wire idataout18;
    wire idataout19;
    wire co8;
    wire idataout20;
    wire idataout21;
    wire co9;
    wire idataout22;
    wire idataout23;
    wire co10;
    wire idataout24;
    wire idataout25;
    wire co11;
    wire idataout26;
    wire idataout27;
    wire co12;
    wire idataout28;
    wire idataout29;
    wire co13;
    wire idataout30;
    wire idataout31;
    wire co15;
    wire co14;

    FD1P3DX FF_31 (.D(idataout0), .SP(Clk_En), .CK(Clock), .CD(Aclr), .Q(Q[0]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_30 (.D(idataout1), .SP(Clk_En), .CK(Clock), .CD(Aclr), .Q(Q[1]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_29 (.D(idataout2), .SP(Clk_En), .CK(Clock), .CD(Aclr), .Q(Q[2]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_28 (.D(idataout3), .SP(Clk_En), .CK(Clock), .CD(Aclr), .Q(Q[3]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_27 (.D(idataout4), .SP(Clk_En), .CK(Clock), .CD(Aclr), .Q(Q[4]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_26 (.D(idataout5), .SP(Clk_En), .CK(Clock), .CD(Aclr), .Q(Q[5]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_25 (.D(idataout6), .SP(Clk_En), .CK(Clock), .CD(Aclr), .Q(Q[6]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_24 (.D(idataout7), .SP(Clk_En), .CK(Clock), .CD(Aclr), .Q(Q[7]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_23 (.D(idataout8), .SP(Clk_En), .CK(Clock), .CD(Aclr), .Q(Q[8]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_22 (.D(idataout9), .SP(Clk_En), .CK(Clock), .CD(Aclr), .Q(Q[9]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_21 (.D(idataout10), .SP(Clk_En), .CK(Clock), .CD(Aclr), .Q(Q[10]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_20 (.D(idataout11), .SP(Clk_En), .CK(Clock), .CD(Aclr), .Q(Q[11]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_19 (.D(idataout12), .SP(Clk_En), .CK(Clock), .CD(Aclr), .Q(Q[12]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_18 (.D(idataout13), .SP(Clk_En), .CK(Clock), .CD(Aclr), .Q(Q[13]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_17 (.D(idataout14), .SP(Clk_En), .CK(Clock), .CD(Aclr), .Q(Q[14]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_16 (.D(idataout15), .SP(Clk_En), .CK(Clock), .CD(Aclr), .Q(Q[15]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_15 (.D(idataout16), .SP(Clk_En), .CK(Clock), .CD(Aclr), .Q(Q[16]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_14 (.D(idataout17), .SP(Clk_En), .CK(Clock), .CD(Aclr), .Q(Q[17]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_13 (.D(idataout18), .SP(Clk_En), .CK(Clock), .CD(Aclr), .Q(Q[18]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_12 (.D(idataout19), .SP(Clk_En), .CK(Clock), .CD(Aclr), .Q(Q[19]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_11 (.D(idataout20), .SP(Clk_En), .CK(Clock), .CD(Aclr), .Q(Q[20]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_10 (.D(idataout21), .SP(Clk_En), .CK(Clock), .CD(Aclr), .Q(Q[21]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_9 (.D(idataout22), .SP(Clk_En), .CK(Clock), .CD(Aclr), .Q(Q[22]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_8 (.D(idataout23), .SP(Clk_En), .CK(Clock), .CD(Aclr), .Q(Q[23]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_7 (.D(idataout24), .SP(Clk_En), .CK(Clock), .CD(Aclr), .Q(Q[24]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_6 (.D(idataout25), .SP(Clk_En), .CK(Clock), .CD(Aclr), .Q(Q[25]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_5 (.D(idataout26), .SP(Clk_En), .CK(Clock), .CD(Aclr), .Q(Q[26]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_4 (.D(idataout27), .SP(Clk_En), .CK(Clock), .CD(Aclr), .Q(Q[27]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_3 (.D(idataout28), .SP(Clk_En), .CK(Clock), .CD(Aclr), .Q(Q[28]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_2 (.D(idataout29), .SP(Clk_En), .CK(Clock), .CD(Aclr), .Q(Q[29]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_1 (.D(idataout30), .SP(Clk_En), .CK(Clock), .CD(Aclr), .Q(Q[30]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_0 (.D(idataout31), .SP(Clk_En), .CK(Clock), .CD(Aclr), .Q(Q[31]))
             /* synthesis GSR="ENABLED" */;

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    FADD2B cnt_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), .B1(scuba_vhi), 
        .CI(scuba_vlo), .COUT(cnt_ci), .S0(), .S1());

    CU2 cnt_0 (.CI(cnt_ci), .PC0(Q[0]), .PC1(Q[1]), .CO(co0), .NC0(idataout0), 
        .NC1(idataout1));

    CU2 cnt_1 (.CI(co0), .PC0(Q[2]), .PC1(Q[3]), .CO(co1), .NC0(idataout2), 
        .NC1(idataout3));

    CU2 cnt_2 (.CI(co1), .PC0(Q[4]), .PC1(Q[5]), .CO(co2), .NC0(idataout4), 
        .NC1(idataout5));

    CU2 cnt_3 (.CI(co2), .PC0(Q[6]), .PC1(Q[7]), .CO(co3), .NC0(idataout6), 
        .NC1(idataout7));

    CU2 cnt_4 (.CI(co3), .PC0(Q[8]), .PC1(Q[9]), .CO(co4), .NC0(idataout8), 
        .NC1(idataout9));

    CU2 cnt_5 (.CI(co4), .PC0(Q[10]), .PC1(Q[11]), .CO(co5), .NC0(idataout10), 
        .NC1(idataout11));

    CU2 cnt_6 (.CI(co5), .PC0(Q[12]), .PC1(Q[13]), .CO(co6), .NC0(idataout12), 
        .NC1(idataout13));

    CU2 cnt_7 (.CI(co6), .PC0(Q[14]), .PC1(Q[15]), .CO(co7), .NC0(idataout14), 
        .NC1(idataout15));

    CU2 cnt_8 (.CI(co7), .PC0(Q[16]), .PC1(Q[17]), .CO(co8), .NC0(idataout16), 
        .NC1(idataout17));

    CU2 cnt_9 (.CI(co8), .PC0(Q[18]), .PC1(Q[19]), .CO(co9), .NC0(idataout18), 
        .NC1(idataout19));

    CU2 cnt_10 (.CI(co9), .PC0(Q[20]), .PC1(Q[21]), .CO(co10), .NC0(idataout20), 
        .NC1(idataout21));

    CU2 cnt_11 (.CI(co10), .PC0(Q[22]), .PC1(Q[23]), .CO(co11), .NC0(idataout22), 
        .NC1(idataout23));

    CU2 cnt_12 (.CI(co11), .PC0(Q[24]), .PC1(Q[25]), .CO(co12), .NC0(idataout24), 
        .NC1(idataout25));

    CU2 cnt_13 (.CI(co12), .PC0(Q[26]), .PC1(Q[27]), .CO(co13), .NC0(idataout26), 
        .NC1(idataout27));

    CU2 cnt_14 (.CI(co13), .PC0(Q[28]), .PC1(Q[29]), .CO(co14), .NC0(idataout28), 
        .NC1(idataout29));

    CU2 cnt_15 (.CI(co14), .PC0(Q[30]), .PC1(Q[31]), .CO(co15), .NC0(idataout30), 
        .NC1(idataout31));



    // exemplar begin
    // exemplar attribute FF_31 GSR ENABLED
    // exemplar attribute FF_30 GSR ENABLED
    // exemplar attribute FF_29 GSR ENABLED
    // exemplar attribute FF_28 GSR ENABLED
    // exemplar attribute FF_27 GSR ENABLED
    // exemplar attribute FF_26 GSR ENABLED
    // exemplar attribute FF_25 GSR ENABLED
    // exemplar attribute FF_24 GSR ENABLED
    // exemplar attribute FF_23 GSR ENABLED
    // exemplar attribute FF_22 GSR ENABLED
    // exemplar attribute FF_21 GSR ENABLED
    // exemplar attribute FF_20 GSR ENABLED
    // exemplar attribute FF_19 GSR ENABLED
    // exemplar attribute FF_18 GSR ENABLED
    // exemplar attribute FF_17 GSR ENABLED
    // exemplar attribute FF_16 GSR ENABLED
    // exemplar attribute FF_15 GSR ENABLED
    // exemplar attribute FF_14 GSR ENABLED
    // exemplar attribute FF_13 GSR ENABLED
    // exemplar attribute FF_12 GSR ENABLED
    // exemplar attribute FF_11 GSR ENABLED
    // exemplar attribute FF_10 GSR ENABLED
    // exemplar attribute FF_9 GSR ENABLED
    // exemplar attribute FF_8 GSR ENABLED
    // exemplar attribute FF_7 GSR ENABLED
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar end

endmodule
