/* Verilog module instantiation template generated by SCUBA Diamond_2.2_Production (99) */
/* Module Version: 4.3 */
/* Thu Aug 29 17:31:14 2013 */

/* parameterized module instance */
PMcounter __ (.Clock( ), .Clk_En( ), .Aclr( ), .Q( ));
